### ISSUE TITLE
Síntesis Webinar. Buenas prácticas en la gestión de proyectos de software

### ISSUE THREAD

**Issue by JulioCesar69** [SistemasTecTlaxiaco/sintesis-JulioCesar69#2]
[sintesis webinar.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-JulioCesar69/files/7118678/sintesis.webinar.pdf)

**Comment by antoniio** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
